// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CandleInterval.
const (
	N15m CandleInterval = "15m"
	N1d  CandleInterval = "1d"
	N1h  CandleInterval = "1h"
	N1m  CandleInterval = "1m"
	N4h  CandleInterval = "4h"
	N5m  CandleInterval = "5m"
)

// Defines values for InstrumentStatus.
const (
	Suspended InstrumentStatus = "suspended"
	Trading   InstrumentStatus = "trading"
)

// Defines values for Market.
const (
	Spot Market = "spot"
	UsdM Market = "usd_m"
)

// Defines values for UserInfoAccessMode.
const (
	Authenticated UserInfoAccessMode = "authenticated"
)

// Defines values for Venue.
const (
	Binance Venue = "binance"
)

// CandleInterval defines model for CandleInterval.
type CandleInterval string

// CursorPageData defines model for CursorPageData.
type CursorPageData struct {
	HasMore    bool         `json:"hasMore"`
	NextCursor string       `json:"nextCursor"`
	Records    []JsonObject `json:"records"`
	Total      int64        `json:"total"`
}

// CursorPageResponse defines model for CursorPageResponse.
type CursorPageResponse struct {
	Code int32          `json:"code"`
	Data CursorPageData `json:"data"`
	Msg  string         `json:"msg"`
}

// DecimalString defines model for DecimalString.
type DecimalString = string

// FinancialResourceId defines model for FinancialResourceId.
type FinancialResourceId = openapi_types.UUID

// InAppCursorPageData defines model for InAppCursorPageData.
type InAppCursorPageData struct {
	HasMore     bool         `json:"hasMore"`
	NextCursor  string       `json:"nextCursor"`
	Records     []JsonObject `json:"records"`
	Total       int64        `json:"total"`
	UnreadCount int64        `json:"unreadCount"`
}

// InAppCursorPageResponse defines model for InAppCursorPageResponse.
type InAppCursorPageResponse struct {
	Code int32               `json:"code"`
	Data InAppCursorPageData `json:"data"`
	Msg  string              `json:"msg"`
}

// InstrumentStatus defines model for InstrumentStatus.
type InstrumentStatus string

// JsonObject defines model for JsonObject.
type JsonObject map[string]interface{}

// LoginData defines model for LoginData.
type LoginData struct {
	AccessToken string `json:"accessToken"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Code int32     `json:"code"`
	Data LoginData `json:"data"`
	Msg  string    `json:"msg"`
}

// Market defines model for Market.
type Market string

// MarketCandle defines model for MarketCandle.
type MarketCandle struct {
	BaseVolume   DecimalString       `json:"baseVolume"`
	Close        DecimalString       `json:"close"`
	CloseTime    time.Time           `json:"closeTime"`
	High         DecimalString       `json:"high"`
	InstrumentId FinancialResourceId `json:"instrumentId"`
	Interval     CandleInterval      `json:"interval"`
	IsClosed     bool                `json:"isClosed"`
	Low          DecimalString       `json:"low"`
	Open         DecimalString       `json:"open"`
	OpenTime     time.Time           `json:"openTime"`
}

// MarketCandlePageData defines model for MarketCandlePageData.
type MarketCandlePageData struct {
	HasMore    bool           `json:"hasMore"`
	NextCursor string         `json:"nextCursor"`
	Records    []MarketCandle `json:"records"`
	Total      int64          `json:"total"`
}

// MarketCandlePageResponse defines model for MarketCandlePageResponse.
type MarketCandlePageResponse struct {
	Code int32                `json:"code"`
	Data MarketCandlePageData `json:"data"`
	Msg  string               `json:"msg"`
}

// MarketSymbol defines model for MarketSymbol.
type MarketSymbol struct {
	BaseAsset    string              `json:"baseAsset"`
	Id           FinancialResourceId `json:"id"`
	Market       Market              `json:"market"`
	MinNotional  DecimalString       `json:"minNotional"`
	MinQuantity  DecimalString       `json:"minQuantity"`
	NativeSymbol string              `json:"nativeSymbol"`
	PriceTick    DecimalString       `json:"priceTick"`
	QuantityStep DecimalString       `json:"quantityStep"`
	QuoteAsset   string              `json:"quoteAsset"`
	Status       InstrumentStatus    `json:"status"`
	UpdatedAt    time.Time           `json:"updatedAt"`
	Venue        Venue               `json:"venue"`
}

// MarketSymbolPageData defines model for MarketSymbolPageData.
type MarketSymbolPageData struct {
	HasMore    bool           `json:"hasMore"`
	NextCursor string         `json:"nextCursor"`
	Records    []MarketSymbol `json:"records"`
	Total      int64          `json:"total"`
}

// MarketSymbolPageResponse defines model for MarketSymbolPageResponse.
type MarketSymbolPageResponse struct {
	Code int32                `json:"code"`
	Data MarketSymbolPageData `json:"data"`
	Msg  string               `json:"msg"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail    string `json:"detail"`
	RequestId string `json:"requestId"`
	Status    int32  `json:"status"`
	Title     string `json:"title"`
	Type      string `json:"type"`
}

// ReauthData defines model for ReauthData.
type ReauthData struct {
	ReauthToken string `json:"reauthToken"`
}

// ReauthRequest defines model for ReauthRequest.
type ReauthRequest struct {
	Password string `json:"password"`
}

// ReauthResponse defines model for ReauthResponse.
type ReauthResponse struct {
	Code int32      `json:"code"`
	Data ReauthData `json:"data"`
	Msg  string     `json:"msg"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Code int32       `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	AccessMode  UserInfoAccessMode `json:"accessMode"`
	Avatar      *string            `json:"avatar,omitempty"`
	Email       *string            `json:"email,omitempty"`
	Permissions []string           `json:"permissions"`
	RoleCodes   []string           `json:"roleCodes"`
	UserId      int64              `json:"userId"`
	Username    string             `json:"username"`
}

// UserInfoAccessMode defines model for UserInfo.AccessMode.
type UserInfoAccessMode string

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Code int32    `json:"code"`
	Data UserInfo `json:"data"`
	Msg  string   `json:"msg"`
}

// Venue defines model for Venue.
type Venue string

// WatchlistCreateRequest defines model for WatchlistCreateRequest.
type WatchlistCreateRequest struct {
	InstrumentId FinancialResourceId `json:"instrumentId"`
	Interval     CandleInterval      `json:"interval"`
}

// WatchlistItem defines model for WatchlistItem.
type WatchlistItem struct {
	CreatedAt    time.Time           `json:"createdAt"`
	Id           FinancialResourceId `json:"id"`
	InstrumentId FinancialResourceId `json:"instrumentId"`
	Interval     CandleInterval      `json:"interval"`
	OwnerUserId  int64               `json:"ownerUserId"`
}

// WatchlistItemResponse defines model for WatchlistItemResponse.
type WatchlistItemResponse struct {
	Code int32         `json:"code"`
	Data WatchlistItem `json:"data"`
	Msg  string        `json:"msg"`
}

// WatchlistPageData defines model for WatchlistPageData.
type WatchlistPageData struct {
	HasMore    bool            `json:"hasMore"`
	NextCursor string          `json:"nextCursor"`
	Records    []WatchlistItem `json:"records"`
	Total      int64           `json:"total"`
}

// WatchlistPageResponse defines model for WatchlistPageResponse.
type WatchlistPageResponse struct {
	Code int32             `json:"code"`
	Data WatchlistPageData `json:"data"`
	Msg  string            `json:"msg"`
}

// AgentCode defines model for AgentCode.
type AgentCode = string

// AgentId defines model for AgentId.
type AgentId = int64

// ButtonId defines model for ButtonId.
type ButtonId = int64

// ChannelId defines model for ChannelId.
type ChannelId = int64

// ConfigId defines model for ConfigId.
type ConfigId = int64

// Cursor defines model for Cursor.
type Cursor = string

// DefinitionId defines model for DefinitionId.
type DefinitionId = int64

// DeliveryId defines model for DeliveryId.
type DeliveryId = int64

// EntryKey defines model for EntryKey.
type EntryKey = string

// ExecutionId defines model for ExecutionId.
type ExecutionId = int64

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Keyword defines model for Keyword.
type Keyword = string

// Limit defines model for Limit.
type Limit = int

// MenuId defines model for MenuId.
type MenuId = int64

// NewsId defines model for NewsId.
type NewsId = int64

// RoleId defines model for RoleId.
type RoleId = int64

// SessionId defines model for SessionId.
type SessionId = int64

// TaskCode defines model for TaskCode.
type TaskCode = string

// UserId defines model for UserId.
type UserId = int64

// WorkflowCode defines model for WorkflowCode.
type WorkflowCode = string

// WorkflowSecret defines model for WorkflowSecret.
type WorkflowSecret = string

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Conflict defines model for Conflict.
type Conflict = Problem

// CursorPage defines model for CursorPage.
type CursorPage = CursorPageResponse

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// InAppCursorPage defines model for InAppCursorPage.
type InAppCursorPage = InAppCursorPageResponse

// NotFound defines model for NotFound.
type NotFound = Problem

// Success defines model for Success.
type Success = SuccessResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// ListPushDeliveriesParams defines parameters for ListPushDeliveries.
type ListPushDeliveriesParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor               *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit                *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	Keyword              *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`
	WorkflowDefinitionId *int64   `form:"workflowDefinitionId,omitempty" json:"workflowDefinitionId,omitempty"`
	ChannelType          *string  `form:"channelType,omitempty" json:"channelType,omitempty"`
	DeliveryStatus       *string  `form:"deliveryStatus,omitempty" json:"deliveryStatus,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor   *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Id       *int64  `form:"id,omitempty" json:"id,omitempty"`
	Username *string `form:"username,omitempty" json:"username,omitempty"`
	Gender   *string `form:"gender,omitempty" json:"gender,omitempty"`
	Phone    *string `form:"phone,omitempty" json:"phone,omitempty"`
	Email    *string `form:"email,omitempty" json:"email,omitempty"`
	IsActive *bool   `form:"isActive,omitempty" json:"isActive,omitempty"`
}

// ListAssistantSessionsParams defines parameters for ListAssistantSessions.
type ListAssistantSessionsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor    *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	AgentCode string  `form:"agentCode" json:"agentCode"`
}

// GetCurrentAssistantSessionParams defines parameters for GetCurrentAssistantSession.
type GetCurrentAssistantSessionParams struct {
	AgentCode     string `form:"agentCode" json:"agentCode"`
	NewsId        *int64 `form:"newsId,omitempty" json:"newsId,omitempty"`
	ModelConfigId *int64 `form:"modelConfigId,omitempty" json:"modelConfigId,omitempty"`
	ForceNew      *bool  `form:"forceNew,omitempty" json:"forceNew,omitempty"`
}

// ListNewsParams defines parameters for ListNews.
type ListNewsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor  *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	Keyword *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`
}

// ListMarketCandlesParams defines parameters for ListMarketCandles.
type ListMarketCandlesParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor       *Cursor             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit        *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	InstrumentId FinancialResourceId `form:"instrumentId" json:"instrumentId"`
	Interval     CandleInterval      `form:"interval" json:"interval"`
	StartTime    *time.Time          `form:"startTime,omitempty" json:"startTime,omitempty"`
	EndTime      *time.Time          `form:"endTime,omitempty" json:"endTime,omitempty"`
}

// ListMarketSymbolsParams defines parameters for ListMarketSymbols.
type ListMarketSymbolsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor  *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Market  *Market `form:"market,omitempty" json:"market,omitempty"`
	Keyword *string `form:"keyword,omitempty" json:"keyword,omitempty"`
}

// ListNotificationDeliveriesParams defines parameters for ListNotificationDeliveries.
type ListNotificationDeliveriesParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetI18nDictionariesParams defines parameters for GetI18nDictionaries.
type GetI18nDictionariesParams struct {
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// ListRolesParams defines parameters for ListRoles.
type ListRolesParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor      *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit       *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Id          *int64  `form:"id,omitempty" json:"id,omitempty"`
	DisplayName *string `form:"displayName,omitempty" json:"displayName,omitempty"`
	Code        *string `form:"code,omitempty" json:"code,omitempty"`
	Description *string `form:"description,omitempty" json:"description,omitempty"`
	IsEnabled   *bool   `form:"isEnabled,omitempty" json:"isEnabled,omitempty"`
}

// UploadAvatarMultipartBody defines parameters for UploadAvatar.
type UploadAvatarMultipartBody struct {
	Avatar openapi_types.File `json:"avatar"`
}

// ListWatchlistItemsParams defines parameters for ListWatchlistItems.
type ListWatchlistItemsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAllWorkflowExecutionsParams defines parameters for ListAllWorkflowExecutions.
type ListAllWorkflowExecutionsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor                 *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit                  *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	WorkflowDefinitionCode *string  `form:"workflowDefinitionCode,omitempty" json:"workflowDefinitionCode,omitempty"`
	Keyword                *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`
	TriggerType            *string  `form:"triggerType,omitempty" json:"triggerType,omitempty"`
	Status                 *string  `form:"status,omitempty" json:"status,omitempty"`
}

// ListTaskDefinitionPageParams defines parameters for ListTaskDefinitionPage.
type ListTaskDefinitionPageParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor  *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	Keyword *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`
}

// TriggerWorkflowWebhookParams defines parameters for TriggerWorkflowWebhook.
type TriggerWorkflowWebhookParams struct {
	IdempotencyKey  IdempotencyKey `json:"Idempotency-Key"`
	XWorkflowSecret WorkflowSecret `json:"X-Workflow-Secret"`
}

// ListWorkflowExecutionsParams defines parameters for ListWorkflowExecutions.
type ListWorkflowExecutionsParams struct {
	// Cursor Opaque cursor returned by the same route and filter set.
	Cursor      *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit       *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	Keyword     *Keyword `form:"keyword,omitempty" json:"keyword,omitempty"`
	TriggerType *string  `form:"triggerType,omitempty" json:"triggerType,omitempty"`
	Status      *string  `form:"status,omitempty" json:"status,omitempty"`
}

// RunWorkflowParams defines parameters for RunWorkflow.
type RunWorkflowParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// NotificationsWebSocketParams defines parameters for NotificationsWebSocket.
type NotificationsWebSocketParams struct {
	SecWebSocketProtocol string `json:"Sec-WebSocket-Protocol"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = JsonObject

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = JsonObject

// StreamAssistantSessionJSONRequestBody defines body for StreamAssistantSession for application/json ContentType.
type StreamAssistantSessionJSONRequestBody = JsonObject

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ReauthenticateJSONRequestBody defines body for Reauthenticate for application/json ContentType.
type ReauthenticateJSONRequestBody = ReauthRequest

// CreateAiModelJSONRequestBody defines body for CreateAiModel for application/json ContentType.
type CreateAiModelJSONRequestBody = JsonObject

// PatchAiModelJSONRequestBody defines body for PatchAiModel for application/json ContentType.
type PatchAiModelJSONRequestBody = JsonObject

// UpdateAiModelJSONRequestBody defines body for UpdateAiModel for application/json ContentType.
type UpdateAiModelJSONRequestBody = JsonObject

// BindAiModelAgentsJSONRequestBody defines body for BindAiModelAgents for application/json ContentType.
type BindAiModelAgentsJSONRequestBody = JsonObject

// CreateAssistantAgentJSONRequestBody defines body for CreateAssistantAgent for application/json ContentType.
type CreateAssistantAgentJSONRequestBody = JsonObject

// PatchAssistantAgentJSONRequestBody defines body for PatchAssistantAgent for application/json ContentType.
type PatchAssistantAgentJSONRequestBody = JsonObject

// UpdateAssistantAgentJSONRequestBody defines body for UpdateAssistantAgent for application/json ContentType.
type UpdateAssistantAgentJSONRequestBody = JsonObject

// CreateNewsJSONRequestBody defines body for CreateNews for application/json ContentType.
type CreateNewsJSONRequestBody = JsonObject

// UpdateNewsJSONRequestBody defines body for UpdateNews for application/json ContentType.
type UpdateNewsJSONRequestBody = JsonObject

// CreateNotificationChannelJSONRequestBody defines body for CreateNotificationChannel for application/json ContentType.
type CreateNotificationChannelJSONRequestBody = JsonObject

// PatchNotificationChannelJSONRequestBody defines body for PatchNotificationChannel for application/json ContentType.
type PatchNotificationChannelJSONRequestBody = JsonObject

// UpdateNotificationChannelJSONRequestBody defines body for UpdateNotificationChannel for application/json ContentType.
type UpdateNotificationChannelJSONRequestBody = JsonObject

// CreateMenuButtonJSONRequestBody defines body for CreateMenuButton for application/json ContentType.
type CreateMenuButtonJSONRequestBody = JsonObject

// UpdateMenuButtonJSONRequestBody defines body for UpdateMenuButton for application/json ContentType.
type UpdateMenuButtonJSONRequestBody = JsonObject

// CreateMenuJSONRequestBody defines body for CreateMenu for application/json ContentType.
type CreateMenuJSONRequestBody = JsonObject

// UpdateMenuJSONRequestBody defines body for UpdateMenu for application/json ContentType.
type UpdateMenuJSONRequestBody = JsonObject

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = JsonObject

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = JsonObject

// SaveRolePermissionsJSONRequestBody defines body for SaveRolePermissions for application/json ContentType.
type SaveRolePermissionsJSONRequestBody = JsonObject

// UploadAvatarMultipartRequestBody defines body for UploadAvatar for multipart/form-data ContentType.
type UploadAvatarMultipartRequestBody UploadAvatarMultipartBody

// CreateWatchlistItemJSONRequestBody defines body for CreateWatchlistItem for application/json ContentType.
type CreateWatchlistItemJSONRequestBody = WatchlistCreateRequest

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody = JsonObject

// UpdateTaskDefinitionDefaultsJSONRequestBody defines body for UpdateTaskDefinitionDefaults for application/json ContentType.
type UpdateTaskDefinitionDefaultsJSONRequestBody = JsonObject

// ValidateWorkflowJSONRequestBody defines body for ValidateWorkflow for application/json ContentType.
type ValidateWorkflowJSONRequestBody = JsonObject

// TriggerWorkflowWebhookJSONRequestBody defines body for TriggerWorkflowWebhook for application/json ContentType.
type TriggerWorkflowWebhookJSONRequestBody = JsonObject

// UpdateWorkflowJSONRequestBody defines body for UpdateWorkflow for application/json ContentType.
type UpdateWorkflowJSONRequestBody = JsonObject

// RunWorkflowJSONRequestBody defines body for RunWorkflow for application/json ContentType.
type RunWorkflowJSONRequestBody = JsonObject

// UpdateWorkflowRuntimeEntryJSONRequestBody defines body for UpdateWorkflowRuntimeEntry for application/json ContentType.
type UpdateWorkflowRuntimeEntryJSONRequestBody = JsonObject
