services:
  backend:
    build:
      cache_from:
        - type=local,src=/tmp/coinsphere-buildx-cache/backend
      cache_to:
        - type=local,dest=/tmp/coinsphere-buildx-cache-next/backend,mode=max

  web:
    build:
      cache_from:
        - type=local,src=/tmp/coinsphere-buildx-cache/frontend
      cache_to:
        - type=local,dest=/tmp/coinsphere-buildx-cache-next/frontend,mode=max
