// Package pluginbuild renders the compile-time plugin registries.
package pluginbuild

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path"
	"sort"
	"strconv"
	"strings"

	"coinsphere/backend/plugin/manifest"
	"github.com/pressly/goose/v3"
)

func RenderBackend(plugins []manifest.Package) ([]byte, error) {
	return RenderBackendWithDependencies(plugins, nil)
}

func RenderBackendWithDependencies(plugins []manifest.Package, available map[string]string) ([]byte, error) {
	var err error
	plugins, err = manifest.SortByDependenciesWithAvailable(plugins, available)
	if err != nil {
		return nil, err
	}
	var source strings.Builder
	source.WriteString("// Code generated by coinsphere plugin tooling; DO NOT EDIT.\n")
	source.WriteString("package pluginregistry\n\n")
	source.WriteString("import \"coinsphere/backend/plugin/sdk\"\n")
	for index, plugin := range plugins {
		fmt.Fprintf(&source, "import plugin%d %s\n", index, strconv.Quote(plugin.Manifest.Backend.Module))
	}
	source.WriteString("\nvar CompiledPlugins = []sdk.PluginDescriptor{\n")
	for _, plugin := range plugins {
		contributes := append([]string(nil), plugin.Manifest.Contributes...)
		sort.Strings(contributes)
		fmt.Fprintf(&source, "{ID: %s, Name: %s, Menu: sdk.PluginMenuDescriptor{Mode: %s, Title: %s, Icon: %s, Parent: %s}, Version: %s, Contributes: %#v, RequiresPlugins: %#v, Permissions: []sdk.PermissionDescriptor{",
			strconv.Quote(plugin.Manifest.ID), strconv.Quote(plugin.Manifest.Name), strconv.Quote(plugin.Manifest.Menu.Mode), strconv.Quote(plugin.Manifest.Menu.Title), strconv.Quote(plugin.Manifest.Menu.Icon), strconv.Quote(plugin.Manifest.Menu.Parent), strconv.Quote(plugin.Manifest.Version), contributes, plugin.Manifest.RequiresPlugins)
		for _, p := range plugin.Manifest.Permissions {
			fmt.Fprintf(&source, "{Code:%s,Title:%s,Protected:%t},", strconv.Quote(p.Code), strconv.Quote(p.Title), p.Protected)
		}
		source.WriteString("}},\n")
	}
	source.WriteString("}\n\nfunc RegisterAll(registry *sdk.Registry, host sdk.Host, enabled map[string]bool) error {\n")
	for index := range plugins {
		fmt.Fprintf(&source, "if enabled[CompiledPlugins[%d].ID] { if err := registry.RegisterPlugin(CompiledPlugins[%d],host,plugin%d.Register); err != nil { return err } }\n", index, index, index)
	}
	source.WriteString("return nil\n}\n")
	source.WriteString("\nvar CompiledMigrationVersions = map[string]int64{\n")
	for _, plugin := range plugins {
		entries, err := os.ReadDir(plugin.MigrationsPath)
		if err != nil {
			return nil, fmt.Errorf("read migrations for %s: %w", plugin.Manifest.ID, err)
		}
		var latest int64
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".sql") {
				continue
			}
			version, err := goose.NumericComponent(entry.Name())
			if err != nil {
				return nil, err
			}
			latest = max(latest, version)
		}
		if latest == 0 {
			return nil, fmt.Errorf("migration bundle for %s is empty", plugin.Manifest.ID)
		}
		fmt.Fprintf(&source, "%s: %d,\n", strconv.Quote(plugin.Manifest.ID), latest)
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format backend registry: %w", err)
	}
	return formatted, nil
}

func RenderFrontend(plugins []manifest.Package) ([]byte, error) {
	return RenderFrontendWithDependencies(plugins, nil)
}

func RenderFrontendWithDependencies(plugins []manifest.Package, available map[string]string) ([]byte, error) {
	var err error
	plugins, err = manifest.SortByDependenciesWithAvailable(plugins, available)
	if err != nil {
		return nil, err
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by coinsphere plugin tooling; DO NOT EDIT.\n")
	source.WriteString("import type { FrontendPluginModule } from './sdk'\n\n")
	source.WriteString("export interface FrontendPluginRegistration {\n")
	source.WriteString("  readonly id: string\n  readonly version: string\n  readonly load: () => Promise<FrontendPluginModule>\n}\n\n")
	source.WriteString("export const frontendPlugins: readonly FrontendPluginRegistration[] = [\n")
	directories := make(map[string]string, len(plugins))
	for _, plugin := range plugins {
		directory := strings.NewReplacer(".", "_", "-", "_").Replace(plugin.Manifest.ID)
		if previous := directories[directory]; previous != "" {
			return nil, fmt.Errorf("plugin ids %q and %q map to the same frontend directory", previous, plugin.Manifest.ID)
		}
		directories[directory] = plugin.Manifest.ID
		entry := "./installed/" + directory + "/" + strings.TrimPrefix(path.Clean(plugin.Manifest.Frontend.Entry), "./")
		entry = strings.TrimSuffix(entry, ".ts")
		id, _ := json.Marshal(plugin.Manifest.ID)
		version, _ := json.Marshal(plugin.Manifest.Version)
		importPath, _ := json.Marshal(entry)
		fmt.Fprintf(&source, "  { id: %s, version: %s, load: () => import(%s) },\n", id, version, importPath)
	}
	source.WriteString("]\n")
	return source.Bytes(), nil
}

func sortedPlugins(plugins []manifest.Package) []manifest.Package {
	result := append([]manifest.Package(nil), plugins...)
	sort.Slice(result, func(i, j int) bool { return result[i].Manifest.ID < result[j].Manifest.ID })
	return result
}
