// Code generated by coinsphere plugin tooling; DO NOT EDIT.
import type { FrontendPluginModule } from './sdk'

export interface FrontendPluginRegistration {
  readonly id: string
  readonly version: string
  readonly load: () => Promise<FrontendPluginModule>
}

export const frontendPlugins: readonly FrontendPluginRegistration[] = []
