// Code generated by coinsphere plugin tooling; DO NOT EDIT.
export interface FrontendPluginRegistration {
  readonly id: string
  readonly version: string
  readonly load: () => Promise<unknown>
}

export const frontendPlugins: readonly FrontendPluginRegistration[] = []
